# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pro_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
from PyQt5.QtCore import QVariantAnimation as Animation
from PyQt5.QtCore import pyqtSignal, Qt

class Hover(QPushButton):
    enteredSignal = pyqtSignal()
    leavedSignal = pyqtSignal()

    def enterEvent(self, event):
        super().enterEvent(event)
        self.enteredSignal.emit()
    def leaveEvent(self, event):
        super().leaveEvent(event)
        self.leavedSignal.emit()

class Ui_Proto(object):
    def setupUi(self, Proto):
        Proto.setObjectName("Proto")
        Proto.resize(1360, 682)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Protokol/ico/icon-512-maskable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Proto.setWindowIcon(icon)
        Proto.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Proto)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1365, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setAutoFillBackground(True)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.MdiFIO = QtWidgets.QMdiArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MdiFIO.sizePolicy().hasHeightForWidth())
        self.MdiFIO.setSizePolicy(sizePolicy)
        self.MdiFIO.setMaximumSize(QtCore.QSize(300, 16777215))
        self.MdiFIO.setAutoFillBackground(True)
        self.MdiFIO.setStyleSheet("")
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.MdiFIO.setBackground(brush)
        self.MdiFIO.setObjectName("MdiFIO")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setAcceptDrops(False)
        self.subwindow.setAutoFillBackground(False)
        self.subwindow.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.subwindow.setObjectName("subwindow")
        self.MdiFIO.addSubWindow(self.subwindow)
        
        self.subwindow.showMaximized()
        self.subwindow.setWindowFlag(Qt.FramelessWindowHint)  

        self.layoutWidget = QtWidgets.QWidget(self.subwindow)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 258, 232))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridMidiFIO = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridMidiFIO.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridMidiFIO.setContentsMargins(0, 0, 0, 6)
        self.gridMidiFIO.setVerticalSpacing(6)
        self.gridMidiFIO.setObjectName("gridMidiFIO")
        self.rvk = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.rvk.setFont(font)
        self.rvk.setStyleSheet("QComboBox{\n"
        "    position: absolute;\n"
        "    border: 0;\n"
        "    padding: 10px;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(92, 169, 165);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QComboBox:focus{\n"
        "    outline: none;\n"
        "}")
        self.rvk.setObjectName("rvk")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.rvk.addItem("")
        self.gridMidiFIO.addWidget(self.rvk, 5, 0, 1, 1)
        self.gender = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setAutoFillBackground(False)
        self.gender.setStyleSheet("QComboBox{\n"
        "    position: absolute;\n"
        "    border: 0;\n"
        "    padding: 10px;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(92, 169, 165);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}\n"
        "QComboBox:focus{\n"
        "    outline: none;\n"
        "}")
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gridMidiFIO.addWidget(self.gender, 0, 0, 1, 1)
        self.NameLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.gridMidiFIO.addWidget(self.NameLabel, 1, 0, 1, 1)
        self.BirthDayLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BirthDayLabel.setFont(font)
        self.BirthDayLabel.setObjectName("BirthDayLabel")
        self.gridMidiFIO.addWidget(self.BirthDayLabel, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 10px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}\n"
        "\n"
        "")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setObjectName("lineEdit")
        self.gridMidiFIO.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 10px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}\n"
        "\n"
        "")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridMidiFIO.addWidget(self.lineEdit_2, 4, 0, 1, 1)
        self.gridMidiFIO.setRowStretch(0, 6)
        self.MdiMedical = QtWidgets.QMdiArea(self.splitter)
        self.MdiMedical.setAutoFillBackground(False)
        self.MdiMedical.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.MdiMedical.setObjectName("MdiMedical")
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.subwindow_3.setObjectName("subwindow_3")
        self.MdiMedical.addSubWindow(self.subwindow_3)
        self.subwindow_3.showMaximized()
        self.stackedWidget = QtWidgets.QStackedWidget(self.subwindow_3)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 731, 621))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 20, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8stFiels = QtWidgets.QLabel(self.page)
        self.label_8stFiels.setGeometry(QtCore.QRect(220, 310, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8stFiels.setFont(font)
        self.label_8stFiels.setObjectName("label_8stFiels")
        self.lineEdit_8th = QtWidgets.QTextEdit(self.page)
        self.lineEdit_8th.setGeometry(QtCore.QRect(220, 330, 500, 61))
        self.lineEdit_8th.setStyleSheet("QTextEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QTextEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_8th.setObjectName("lineEdit_8th")
        self.lineEdit_7th_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_7th_2.setGeometry(QtCore.QRect(388, 180, 165, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7th_2.setFont(font)
        self.lineEdit_7th_2.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_7th_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7th_2.setPlaceholderText("")
        self.lineEdit_7th_2.setObjectName("lineEdit_7th_2")
        self.lineEdit_1st = QtWidgets.QLineEdit(self.page)
        self.lineEdit_1st.setGeometry(QtCore.QRect(220, 60, 500, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_1st.setFont(font)
        self.lineEdit_1st.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_1st.setCursorPosition(0)
        self.lineEdit_1st.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1st.setDragEnabled(False)
        self.lineEdit_1st.setObjectName("lineEdit_1st")
        self.lineEdit_3th_3 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3th_3.setGeometry(QtCore.QRect(555, 180, 165, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_3.setFont(font)
        self.lineEdit_3th_3.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3th_3.setPlaceholderText("")
        self.lineEdit_3th_3.setObjectName("lineEdit_3th_3")
        self.lineEdit_3th_1 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3th_1.setGeometry(QtCore.QRect(220, 120, 248, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_1.setFont(font)
        self.lineEdit_3th_1.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3th_1.setPlaceholderText("")
        self.lineEdit_3th_1.setObjectName("lineEdit_3th_1")
        self.label_7stFiels = QtWidgets.QLabel(self.page)
        self.label_7stFiels.setGeometry(QtCore.QRect(220, 160, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7stFiels.setFont(font)
        self.label_7stFiels.setObjectName("label_7stFiels")
        self.label_3thFiels = QtWidgets.QLabel(self.page)
        self.label_3thFiels.setGeometry(QtCore.QRect(220, 100, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3thFiels.setFont(font)
        self.label_3thFiels.setObjectName("label_3thFiels")
        self.lineEdit_3th_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_3th_2.setGeometry(QtCore.QRect(472, 120, 248, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_2.setFont(font)
        self.lineEdit_3th_2.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3th_2.setObjectName("lineEdit_3th_2")
        self.labelDoctor = QtWidgets.QLabel(self.page)
        self.labelDoctor.setGeometry(QtCore.QRect(220, 20, 500, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDoctor.setFont(font)
        self.labelDoctor.setObjectName("labelDoctor")
        self.label_1stFiels = QtWidgets.QLabel(self.page)
        self.label_1stFiels.setGeometry(QtCore.QRect(220, 40, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_1stFiels.setFont(font)
        self.label_1stFiels.setObjectName("label_1stFiels")
        self.lineEdit_7th_1 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_7th_1.setGeometry(QtCore.QRect(220, 180, 165, 31))
        self.lineEdit_7th_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7th_1.setFont(font)
        self.lineEdit_7th_1.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_7th_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7th_1.setPlaceholderText("")
        self.lineEdit_7th_1.setObjectName("lineEdit_7th_1")
        self.label_7stFiels_2 = QtWidgets.QLabel(self.page)
        self.label_7stFiels_2.setGeometry(QtCore.QRect(220, 220, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7stFiels_2.setFont(font)
        self.label_7stFiels_2.setObjectName("label_7stFiels_2")
        self.lineEdit_8th_2 = QtWidgets.QTextEdit(self.page)
        self.lineEdit_8th_2.setGeometry(QtCore.QRect(220, 240, 500, 61))
        self.lineEdit_8th_2.setStyleSheet("QTextEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QTextEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_8th_2.setObjectName("lineEdit_8th_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_7stFiels_3 = QtWidgets.QLabel(self.page_2)
        self.label_7stFiels_3.setGeometry(QtCore.QRect(220, 220, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7stFiels_3.setFont(font)
        self.label_7stFiels_3.setObjectName("label_7stFiels_3")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_7th_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_7th_3.setGeometry(QtCore.QRect(388, 180, 165, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7th_3.setFont(font)
        self.lineEdit_7th_3.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_7th_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7th_3.setPlaceholderText("")
        self.lineEdit_7th_3.setObjectName("lineEdit_7th_3")
        self.lineEdit_3th_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3th_4.setGeometry(QtCore.QRect(555, 180, 165, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_4.setFont(font)
        self.lineEdit_3th_4.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3th_4.setPlaceholderText("")
        self.lineEdit_3th_4.setObjectName("lineEdit_3th_4")
        self.lineEdit_3th_5 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3th_5.setGeometry(QtCore.QRect(472, 120, 248, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_5.setFont(font)
        self.lineEdit_3th_5.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3th_5.setObjectName("lineEdit_3th_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 40, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_1stFiels_2 = QtWidgets.QLabel(self.page_2)
        self.label_1stFiels_2.setGeometry(QtCore.QRect(220, 40, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_1stFiels_2.setFont(font)
        self.label_1stFiels_2.setObjectName("label_1stFiels_2")
        self.lineEdit_8th_3 = QtWidgets.QTextEdit(self.page_2)
        self.lineEdit_8th_3.setGeometry(QtCore.QRect(220, 240, 500, 61))
        self.lineEdit_8th_3.setStyleSheet("QTextEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QTextEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_8th_3.setObjectName("lineEdit_8th_3")
        self.lineEdit_3th_6 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3th_6.setGeometry(QtCore.QRect(220, 120, 248, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_3th_6.setFont(font)
        self.lineEdit_3th_6.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_3th_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3th_6.setPlaceholderText("")
        self.lineEdit_3th_6.setObjectName("lineEdit_3th_6")
        self.lineEdit_1st_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_1st_2.setGeometry(QtCore.QRect(220, 60, 500, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_1st_2.setFont(font)
        self.lineEdit_1st_2.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_1st_2.setCursorPosition(0)
        self.lineEdit_1st_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1st_2.setDragEnabled(False)
        self.lineEdit_1st_2.setObjectName("lineEdit_1st_2")
        self.lineEdit_8th_4 = QtWidgets.QTextEdit(self.page_2)
        self.lineEdit_8th_4.setGeometry(QtCore.QRect(220, 330, 500, 61))
        self.lineEdit_8th_4.setStyleSheet("QTextEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QTextEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_8th_4.setObjectName("lineEdit_8th_4")
        self.label_7stFiels_4 = QtWidgets.QLabel(self.page_2)
        self.label_7stFiels_4.setGeometry(QtCore.QRect(220, 160, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7stFiels_4.setFont(font)
        self.label_7stFiels_4.setObjectName("label_7stFiels_4")
        self.label_3thFiels_2 = QtWidgets.QLabel(self.page_2)
        self.label_3thFiels_2.setGeometry(QtCore.QRect(220, 100, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3thFiels_2.setFont(font)
        self.label_3thFiels_2.setObjectName("label_3thFiels_2")
        self.lineEdit_7th_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_7th_4.setGeometry(QtCore.QRect(220, 180, 165, 31))
        self.lineEdit_7th_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_7th_4.setFont(font)
        self.lineEdit_7th_4.setStyleSheet("QLineEdit{\n"
        "    border: 0;\n"
        "    border-bottom: 2px;\n"
        "    border-style: solid;\n"
        "    border-color: rgb(143, 148, 165, 1);\n"
        "    background-color: rgb(255, 255, 255);\n"
        "    padding: 5px\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    transition-duration: 0.7s;\n"
        "    transition-timing-function: ease-in-out;\n"
        "    outline: none;\n"
        "    border-color: limegreen;\n"
        "}")
        self.lineEdit_7th_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7th_4.setPlaceholderText("")
        self.lineEdit_7th_4.setObjectName("lineEdit_7th_4")
        self.labelDoctor_2 = QtWidgets.QLabel(self.page_2)
        self.labelDoctor_2.setGeometry(QtCore.QRect(220, 20, 500, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelDoctor_2.setFont(font)
        self.labelDoctor_2.setObjectName("labelDoctor_2")
        self.label_8stFiels_2 = QtWidgets.QLabel(self.page_2)
        self.label_8stFiels_2.setGeometry(QtCore.QRect(220, 310, 500, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8stFiels_2.setFont(font)
        self.label_8stFiels_2.setObjectName("label_8stFiels_2")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.subwindow_3)
        self.pushButton.setGeometry(QtCore.QRect(710, 10, 21, 21))
        self.pushButton.setStyleSheet("QPushButton{\n"
        "    background-color: rgba(245, 245, 245, 0.4);\n"
        "    border-radius: 4px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: rgba(51, 202, 152, 0.2);\n"
        "    border-radius: 4px;\n"
        "}"
        "QPushButton:focus{\n"
        "    background-color: rgba(51, 202, 152, 0.7);\n"
        "}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ico/Рисунок2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        #shadow = DropShadow(blurRadius = 0, xOffset = 3, yOffset = 3)
        #self.pushButton.setGraphicsEffect(shadow)
        self.pushButton_2 = QtWidgets.QPushButton(self.subwindow_3)
        self.pushButton_2.setGeometry(QtCore.QRect(689, 10, 21, 21))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
        "    background-color: rgba(245, 245, 245, 0.4);\n"
        "    border-radius: 4px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: rgba(51, 202, 152, 0.2);\n"
        "    border-radius: 7px;\n"
        "}"
        "QPushButton:focus{\n"
        "    background-color: rgba(51, 202, 152, 0.7);\n"
        "}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/Рисунок1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.MdiSuitability = QtWidgets.QMdiArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MdiSuitability.sizePolicy().hasHeightForWidth())
        self.MdiSuitability.setSizePolicy(sizePolicy)
        self.MdiSuitability.setMaximumSize(QtCore.QSize(300, 16777215))
        self.MdiSuitability.setAutoFillBackground(True)
        self.MdiSuitability.setStyleSheet("background-color: rgb(255, 250, 244);")
        self.MdiSuitability.setObjectName("MdiSuitability")
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.subwindow_2.setObjectName("subwindow_2")
        
        self.Add_Button = Hover(self.page_2)
        #self.Add_Button = QtWidgets.QPushButton(self.page_2)
        self.Add_Button.setGeometry(QtCore.QRect(39, 520, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Add_Button.setFont(font)
        self.Add_Button.setStyleSheet("QPushButton{\n"
        "   text-align: right;\n"
        "   border-radius: 2px;\n"
        "   padding-right: 10px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: rgba(51, 202, 152, 0.4);\n"
        "    padding-right: 10px;    \n"
        "    border-radius: 2px;\n"
        "}\n"
        "QPushButton:focus{\n"
        "    background-color: rgb(0, 146, 132);\n"
        "    padding-right: 10px;    \n"
        "    border-radius: 2px;\n"
        "}\n"
        "")
        self.Add_Button.setIconSize(QtCore.QSize(45, 45))
        self.Add_Button.setObjectName("Add_Button")
        
        self.Add_icon = QtWidgets.QLabel(self.page_2)
        self.Add_icon.setEnabled(True)
        self.Add_icon.setGeometry(QtCore.QRect(5, 510, 60, 60))
        self.Add_icon.setMouseTracking(False)
        self.Add_icon.setScaledContents(False)
        self.Add_icon.setWordWrap(False)
        self.Add_icon.setObjectName("Add_icon")
        self.Add_icon.setHidden(True)
        
        self.Save_Button = Hover(self.page_2)
        #self.Save_Button = QtWidgets.QPushButton(self.page_2)
        self.Save_Button.setGeometry(QtCore.QRect(193, 520, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Save_Button.setFont(font)
        self.Save_Button.setStyleSheet("QPushButton{\n"
        "   text-align: right;\n"
        "   border-radius: 2px;\n"
        "   padding-right: 10px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    background-color: rgba(51, 202, 152, 0.4);\n"
        "    padding-right: 10px;    \n"
        "    border-radius: 2px;\n"
        "}\n"
        "QPushButton:focus{\n"
        "    background-color: rgb(0, 146, 132);\n"
        "    padding-right: 10px;    \n"
        "    border-radius: 2px;\n"
        "}\n"
        "")
        self.Save_Button.setIconSize(QtCore.QSize(42, 42))
        self.Save_Button.setCheckable(False)
        self.Save_Button.setAutoDefault(False)
        self.Save_Button.setDefault(False)
        self.Save_Button.setFlat(False)
        self.Save_Button.setObjectName("Save_Button")

        #self.Save_Button.enterEvent

        self.Save_icon = QtWidgets.QLabel(self.page_2)
        self.Save_icon.setEnabled(True)
        self.Save_icon.setGeometry(QtCore.QRect(165, 510, 60, 60))
        self.Save_icon.setMouseTracking(False)
        self.Save_icon.setScaledContents(False)
        self.Save_icon.setWordWrap(False)
        self.Save_icon.setObjectName("Save_icon")
        self.Save_icon.setHidden(True)

        Proto.setCentralWidget(self.centralwidget)

        self.retranslateUi(Proto)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Proto)

    def retranslateUi(self, Proto):
        _translate = QtCore.QCoreApplication.translate
        Proto.setWindowTitle(_translate("Proto", "Протокол ВУЗ"))
        self.subwindow.setWindowTitle(_translate("Proto", "ФИО и ВК"))
        self.rvk.setItemText(0, _translate("Proto", "Барабинский ВК"))
        self.rvk.setItemText(1, _translate("Proto", "Бердский ВК"))
        self.rvk.setItemText(2, _translate("Proto", "Доволенский ВК"))
        self.rvk.setItemText(3, _translate("Proto", "Искитимский ВК"))
        self.rvk.setItemText(4, _translate("Proto", "Карасукский ВК"))
        self.rvk.setItemText(5, _translate("Proto", "Кргатский ВК"))
        self.rvk.setItemText(6, _translate("Proto", "Коченевский ВК"))
        self.rvk.setItemText(7, _translate("Proto", "Куйбышеский ВК"))
        self.rvk.setItemText(8, _translate("Proto", "Ордынский ВК"))
        self.rvk.setItemText(9, _translate("Proto", "Сузунский ВК"))
        self.rvk.setItemText(10, _translate("Proto", "Татарский ВК"))
        self.rvk.setItemText(11, _translate("Proto", "Тогучинский ВК"))
        self.rvk.setItemText(12, _translate("Proto", "Чановский ВК"))
        self.rvk.setItemText(13, _translate("Proto", "Черепановский ВК"))
        self.rvk.setItemText(14, _translate("Proto", "Новосибирский ВК"))
        self.rvk.setItemText(15, _translate("Proto", "Дзежинский ВК"))
        self.rvk.setItemText(16, _translate("Proto", "Кировский ВК"))
        self.rvk.setItemText(17, _translate("Proto", "ЦАО"))
        self.rvk.setItemText(18, _translate("Proto", "Советский ВК"))
        self.gender.setItemText(0, _translate("Proto", "Гражданин"))
        self.gender.setItemText(1, _translate("Proto", "Гражданка"))
        self.NameLabel.setText(_translate("Proto", "Введите ФИО"))
        self.BirthDayLabel.setText(_translate("Proto", "Введите дату рождения"))
        self.lineEdit.setPlaceholderText(_translate("Proto", "Иванов Иван Иванович"))
        self.lineEdit_2.setInputMask(_translate("Proto", "00.00.0000"))
        self.lineEdit_2.setText(_translate("Proto", ".."))
        self.lineEdit_2.setPlaceholderText(_translate("Proto", "01.01.1970"))
        self.subwindow_3.setWindowTitle(_translate("Proto", "Результат осидетельсвования"))
        self.lineEdit_3.setPlaceholderText(_translate("Proto", "Жалоб не предъявляет.   "))
        self.label.setText(_translate("Proto", "Жалобы, если есть"))
        self.label_8stFiels.setText(_translate("Proto", "<html><head/><body><p align=\"center\">Диагноз</p></body></html>"))
        self.lineEdit_7th_2.setInputMask(_translate("Proto", "00.00.0000"))
        self.lineEdit_1st.setInputMask(_translate("Proto", "000/000"))
        self.lineEdit_3th_3.setInputMask(_translate("Proto", "00.00.0000"))
        self.lineEdit_3th_1.setInputMask(_translate("Proto", "999/99"))
        self.label_7stFiels.setText(_translate("Proto", "<html><head/><body><p align=\"center\">ФЛГ ОАК ОАМ</p></body></html>"))
        self.label_3thFiels.setText(_translate("Proto", "<html><head/><body><p align=\"center\">АД и пульс</p></body></html>"))
        self.lineEdit_3th_2.setPlaceholderText(_translate("Proto", "64 удара в минуту"))
        self.labelDoctor.setText(_translate("Proto", "<html><head/><body><p align=\"center\">Терапевт</p></body></html>"))
        self.label_1stFiels.setText(_translate("Proto", "<html><head/><body><p align=\"center\">Введите рост вес</p></body></html>"))
        self.lineEdit_7th_1.setInputMask(_translate("Proto", "00.00.0000"))
        self.label_7stFiels_2.setText(_translate("Proto", "<html><head/><body><p align=\"center\">ФЛГ ОАК ОАМ</p></body></html>"))
        self.label_7stFiels_3.setText(_translate("Proto", "<html><head/><body><p align=\"center\">4</p></body></html>"))
        self.label_2.setText(_translate("Proto", "Жалобы, если есть"))
        self.lineEdit_7th_3.setInputMask(_translate("Proto", "00.00.0000"))
        self.lineEdit_3th_4.setInputMask(_translate("Proto", "00.00.0000"))
        self.lineEdit_3th_5.setPlaceholderText(_translate("Proto", "64 удара в минуту"))
        self.lineEdit_4.setPlaceholderText(_translate("Proto", "Жалоб не предъявляет.   "))
        self.label_1stFiels_2.setText(_translate("Proto", "<html><head/><body><p align=\"center\">1</p></body></html>"))
        self.lineEdit_3th_6.setInputMask(_translate("Proto", "999/99"))
        self.lineEdit_1st_2.setInputMask(_translate("Proto", "000/000"))
        self.label_7stFiels_4.setText(_translate("Proto", "<html><head/><body><p align=\"center\">3</p></body></html>"))
        self.label_3thFiels_2.setText(_translate("Proto", "<html><head/><body><p align=\"center\">2</p></body></html>"))
        self.lineEdit_7th_4.setInputMask(_translate("Proto", "00.00.0000"))
        self.labelDoctor_2.setText(_translate("Proto", "<html><head/><body><p align=\"center\">Офтальмолог</p></body></html>"))
        self.label_8stFiels_2.setText(_translate("Proto", "<html><head/><body><p align=\"center\">8</p></body></html>"))
        self.subwindow_2.setWindowTitle(_translate("Proto", "Годность и ВУЗ"))
        self.Save_Button.setText(_translate("Proto", "Сохранить"))
        self.Save_icon.setText(_translate("Proto", "<html><head/><body><p><img src=\"ico/ico_save/apple--touch-icon.png\"/></p></body></html>"))
        self.Add_Button.setText(_translate("Proto", "Добавить"))
        self.Add_icon.setText(_translate("Proto", "<html><head/><body><p><img src=\"ico/ico_doctr/apple--touch-icon.png\"/></p></body></html>"))

    entered = pyqtSignal()
    leaved = pyqtSignal()
    
    def enterEvent(self, event):
        super().enterEvent(event)
        self.entered.emit()
        # Ui_Proto().setupUi(Ui_Proto).Save_icon.setHidden(False)

    def leavEvent(self, event):
        super().leavEvent(event)
        self.leaved.emit()
